version: '2'
services:
  memcached:
    image: memcached:1.6.6
    ports:
      - "11211:11211"
    networks:
      default:
        ipv4_address: 192.168.16.10
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "8080:80"
    links:
      - isucoin
    networks:
      default:
        ipv4_address: 192.168.16.4

  isucoin:
    environment:
      ISU_APP_PORT:    '5000'
      ISU_DB_HOST:     '192.168.16.3'
      ISU_DB_PORT:     '3306'
      ISU_DB_USER:     'isucon'
      ISU_DB_PASSWORD: 'isucon'
      ISU_DB_NAME:     'isucoin'
      ISU_PUBLIC_DIR:  '/public'
      ISU_MEMCACHED_HOST:     'memcached'
      ISU_MEMCACHED_PORT:     '11211'
    links:
      - mysql
      - memcached
    volumes:
      - ./public:/public
    networks:
      default:
        ipv4_address: 192.168.16.2

  mysql:
    image: mysql:8
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    # development only
    ports:
      - "13306:3306"
    networks:
      default:
        ipv4_address: 192.168.16.3

volumes:
  mysql:
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
          gateway: 192.168.16.1
